### ISSUE TITLE
Firebase setup

### ISSUE THREAD

**Issue by Jgochey** [nss-evening-cohort-28/pos-terminal-jtbn#5]
Do all the stuff needed when setting up the project. These include:
making the updates to the .env file
Create a new firebase project, database, and enable google authentication, etc.
Reference the [webpack instructions](https://github.com/nss-evening-cohort-28/pos-terminal-jtbn/blob/main/webpack-instructions.md) if needed.

**Comment by MJSuttles** [comment]
Setup Firebase Project

1.	https://firebase.google.com/
2.	Get Started
3.	Add a Project
4.	Enter project name => continue => continue
5.	Select “Default account for Firebase”
6.	Create Project
7.	“Your Product Is Ready” => continue

Setup Realtime Database

1.	May have to search for this option
2.	Create database => next
3.	*Start in test mode*
4.	Enable

Setup Authentication

1.	Build => Authentication
2.	Get Started
3.	Click on “Google” => enable
4.	Project support email => select your own address => save

Create App

1.	Click on cog => “Project setting”
2.	Under “Your Apps” => click on “</>” icon
3.	Type app name => do NOT click on “Firebase hosting” => register app => click to continue

Add Keys to .env File

1.	Copy and paste data (API keys and attributes) to .env file
2.	Click on save


Getting Sample Data into Firebase

1.	Go into Realtime Database
2.	Click on “+” symbol
3.	Add name(s) and value(s) => add
4.	Click on item => three dots => Import JSON
5.	Browse and find JSON => open => import
